// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: first_topic.proto

package com.mps.produceData.proto;

public final class CCAssociatedDataEventWrapper {
  private CCAssociatedDataEventWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CCAssociatedDataEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CCAssociatedDataEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CCAssociatedDataEvent_AssociatedDataDTOList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CCAssociatedDataEvent_AssociatedDataDTOList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021first_topic.proto\"\272\001\n\025CCAssociatedData" +
      "Event\022\016\n\006tpName\030\001 \001(\t\022K\n\025associatedDataD" +
      "TOList\030\002 \003(\0132,.CCAssociatedDataEvent.Ass" +
      "ociatedDataDTOList\032D\n\025AssociatedDataDTOL" +
      "ist\022\r\n\005dcode\030\001 \001(\t\022\r\n\005ccode\030\002 \001(\t\022\r\n\005bun" +
      "it\030\003 \001(\tB;\n\031com.mps.produceData.protoB\034C" +
      "CAssociatedDataEventWrapperP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CCAssociatedDataEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CCAssociatedDataEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CCAssociatedDataEvent_descriptor,
        new java.lang.String[] { "TpName", "AssociatedDataDTOList", });
    internal_static_CCAssociatedDataEvent_AssociatedDataDTOList_descriptor =
      internal_static_CCAssociatedDataEvent_descriptor.getNestedTypes().get(0);
    internal_static_CCAssociatedDataEvent_AssociatedDataDTOList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CCAssociatedDataEvent_AssociatedDataDTOList_descriptor,
        new java.lang.String[] { "Dcode", "Ccode", "Bunit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
