// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: first_topic.proto

package com.mps.produceData.proto;

/**
 * Protobuf type {@code CCAssociatedDataEvent}
 */
public final class CCAssociatedDataEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CCAssociatedDataEvent)
    CCAssociatedDataEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CCAssociatedDataEvent.newBuilder() to construct.
  private CCAssociatedDataEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CCAssociatedDataEvent() {
    tpName_ = "";
    associatedDataDTOList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CCAssociatedDataEvent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mps.produceData.proto.CCAssociatedDataEventWrapper.internal_static_CCAssociatedDataEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mps.produceData.proto.CCAssociatedDataEventWrapper.internal_static_CCAssociatedDataEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mps.produceData.proto.CCAssociatedDataEvent.class, com.mps.produceData.proto.CCAssociatedDataEvent.Builder.class);
  }

  public interface AssociatedDataDTOListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CCAssociatedDataEvent.AssociatedDataDTOList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dcode = 1;</code>
     * @return The dcode.
     */
    java.lang.String getDcode();
    /**
     * <code>string dcode = 1;</code>
     * @return The bytes for dcode.
     */
    com.google.protobuf.ByteString
        getDcodeBytes();

    /**
     * <code>string ccode = 2;</code>
     * @return The ccode.
     */
    java.lang.String getCcode();
    /**
     * <code>string ccode = 2;</code>
     * @return The bytes for ccode.
     */
    com.google.protobuf.ByteString
        getCcodeBytes();

    /**
     * <code>string bunit = 3;</code>
     * @return The bunit.
     */
    java.lang.String getBunit();
    /**
     * <code>string bunit = 3;</code>
     * @return The bytes for bunit.
     */
    com.google.protobuf.ByteString
        getBunitBytes();
  }
  /**
   * Protobuf type {@code CCAssociatedDataEvent.AssociatedDataDTOList}
   */
  public static final class AssociatedDataDTOList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CCAssociatedDataEvent.AssociatedDataDTOList)
      AssociatedDataDTOListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AssociatedDataDTOList.newBuilder() to construct.
    private AssociatedDataDTOList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AssociatedDataDTOList() {
      dcode_ = "";
      ccode_ = "";
      bunit_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AssociatedDataDTOList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mps.produceData.proto.CCAssociatedDataEventWrapper.internal_static_CCAssociatedDataEvent_AssociatedDataDTOList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mps.produceData.proto.CCAssociatedDataEventWrapper.internal_static_CCAssociatedDataEvent_AssociatedDataDTOList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.class, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder.class);
    }

    public static final int DCODE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dcode_ = "";
    /**
     * <code>string dcode = 1;</code>
     * @return The dcode.
     */
    @java.lang.Override
    public java.lang.String getDcode() {
      java.lang.Object ref = dcode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dcode_ = s;
        return s;
      }
    }
    /**
     * <code>string dcode = 1;</code>
     * @return The bytes for dcode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDcodeBytes() {
      java.lang.Object ref = dcode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CCODE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ccode_ = "";
    /**
     * <code>string ccode = 2;</code>
     * @return The ccode.
     */
    @java.lang.Override
    public java.lang.String getCcode() {
      java.lang.Object ref = ccode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ccode_ = s;
        return s;
      }
    }
    /**
     * <code>string ccode = 2;</code>
     * @return The bytes for ccode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCcodeBytes() {
      java.lang.Object ref = ccode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ccode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUNIT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bunit_ = "";
    /**
     * <code>string bunit = 3;</code>
     * @return The bunit.
     */
    @java.lang.Override
    public java.lang.String getBunit() {
      java.lang.Object ref = bunit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bunit_ = s;
        return s;
      }
    }
    /**
     * <code>string bunit = 3;</code>
     * @return The bytes for bunit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBunitBytes() {
      java.lang.Object ref = bunit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bunit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dcode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dcode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ccode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ccode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bunit_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bunit_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dcode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dcode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ccode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ccode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bunit_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bunit_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList)) {
        return super.equals(obj);
      }
      com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList other = (com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList) obj;

      if (!getDcode()
          .equals(other.getDcode())) return false;
      if (!getCcode()
          .equals(other.getCcode())) return false;
      if (!getBunit()
          .equals(other.getBunit())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DCODE_FIELD_NUMBER;
      hash = (53 * hash) + getDcode().hashCode();
      hash = (37 * hash) + CCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCcode().hashCode();
      hash = (37 * hash) + BUNIT_FIELD_NUMBER;
      hash = (53 * hash) + getBunit().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CCAssociatedDataEvent.AssociatedDataDTOList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CCAssociatedDataEvent.AssociatedDataDTOList)
        com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mps.produceData.proto.CCAssociatedDataEventWrapper.internal_static_CCAssociatedDataEvent_AssociatedDataDTOList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mps.produceData.proto.CCAssociatedDataEventWrapper.internal_static_CCAssociatedDataEvent_AssociatedDataDTOList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.class, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder.class);
      }

      // Construct using com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        dcode_ = "";
        ccode_ = "";
        bunit_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mps.produceData.proto.CCAssociatedDataEventWrapper.internal_static_CCAssociatedDataEvent_AssociatedDataDTOList_descriptor;
      }

      @java.lang.Override
      public com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList getDefaultInstanceForType() {
        return com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.getDefaultInstance();
      }

      @java.lang.Override
      public com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList build() {
        com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList buildPartial() {
        com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList result = new com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.dcode_ = dcode_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ccode_ = ccode_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.bunit_ = bunit_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList) {
          return mergeFrom((com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList other) {
        if (other == com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.getDefaultInstance()) return this;
        if (!other.getDcode().isEmpty()) {
          dcode_ = other.dcode_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCcode().isEmpty()) {
          ccode_ = other.ccode_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getBunit().isEmpty()) {
          bunit_ = other.bunit_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                dcode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                ccode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                bunit_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object dcode_ = "";
      /**
       * <code>string dcode = 1;</code>
       * @return The dcode.
       */
      public java.lang.String getDcode() {
        java.lang.Object ref = dcode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dcode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dcode = 1;</code>
       * @return The bytes for dcode.
       */
      public com.google.protobuf.ByteString
          getDcodeBytes() {
        java.lang.Object ref = dcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dcode = 1;</code>
       * @param value The dcode to set.
       * @return This builder for chaining.
       */
      public Builder setDcode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dcode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string dcode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDcode() {
        dcode_ = getDefaultInstance().getDcode();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string dcode = 1;</code>
       * @param value The bytes for dcode to set.
       * @return This builder for chaining.
       */
      public Builder setDcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dcode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object ccode_ = "";
      /**
       * <code>string ccode = 2;</code>
       * @return The ccode.
       */
      public java.lang.String getCcode() {
        java.lang.Object ref = ccode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ccode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ccode = 2;</code>
       * @return The bytes for ccode.
       */
      public com.google.protobuf.ByteString
          getCcodeBytes() {
        java.lang.Object ref = ccode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ccode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ccode = 2;</code>
       * @param value The ccode to set.
       * @return This builder for chaining.
       */
      public Builder setCcode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ccode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string ccode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCcode() {
        ccode_ = getDefaultInstance().getCcode();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string ccode = 2;</code>
       * @param value The bytes for ccode to set.
       * @return This builder for chaining.
       */
      public Builder setCcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ccode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object bunit_ = "";
      /**
       * <code>string bunit = 3;</code>
       * @return The bunit.
       */
      public java.lang.String getBunit() {
        java.lang.Object ref = bunit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bunit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bunit = 3;</code>
       * @return The bytes for bunit.
       */
      public com.google.protobuf.ByteString
          getBunitBytes() {
        java.lang.Object ref = bunit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bunit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bunit = 3;</code>
       * @param value The bunit to set.
       * @return This builder for chaining.
       */
      public Builder setBunit(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bunit_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string bunit = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBunit() {
        bunit_ = getDefaultInstance().getBunit();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string bunit = 3;</code>
       * @param value The bytes for bunit to set.
       * @return This builder for chaining.
       */
      public Builder setBunitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        bunit_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CCAssociatedDataEvent.AssociatedDataDTOList)
    }

    // @@protoc_insertion_point(class_scope:CCAssociatedDataEvent.AssociatedDataDTOList)
    private static final com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList();
    }

    public static com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AssociatedDataDTOList>
        PARSER = new com.google.protobuf.AbstractParser<AssociatedDataDTOList>() {
      @java.lang.Override
      public AssociatedDataDTOList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AssociatedDataDTOList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AssociatedDataDTOList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int TPNAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tpName_ = "";
  /**
   * <code>string tpName = 1;</code>
   * @return The tpName.
   */
  @java.lang.Override
  public java.lang.String getTpName() {
    java.lang.Object ref = tpName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tpName_ = s;
      return s;
    }
  }
  /**
   * <code>string tpName = 1;</code>
   * @return The bytes for tpName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTpNameBytes() {
    java.lang.Object ref = tpName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tpName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSOCIATEDDATADTOLIST_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList> associatedDataDTOList_;
  /**
   * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList> getAssociatedDataDTOListList() {
    return associatedDataDTOList_;
  }
  /**
   * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOListOrBuilder> 
      getAssociatedDataDTOListOrBuilderList() {
    return associatedDataDTOList_;
  }
  /**
   * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
   */
  @java.lang.Override
  public int getAssociatedDataDTOListCount() {
    return associatedDataDTOList_.size();
  }
  /**
   * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
   */
  @java.lang.Override
  public com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList getAssociatedDataDTOList(int index) {
    return associatedDataDTOList_.get(index);
  }
  /**
   * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
   */
  @java.lang.Override
  public com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOListOrBuilder getAssociatedDataDTOListOrBuilder(
      int index) {
    return associatedDataDTOList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tpName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tpName_);
    }
    for (int i = 0; i < associatedDataDTOList_.size(); i++) {
      output.writeMessage(2, associatedDataDTOList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tpName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tpName_);
    }
    for (int i = 0; i < associatedDataDTOList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, associatedDataDTOList_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mps.produceData.proto.CCAssociatedDataEvent)) {
      return super.equals(obj);
    }
    com.mps.produceData.proto.CCAssociatedDataEvent other = (com.mps.produceData.proto.CCAssociatedDataEvent) obj;

    if (!getTpName()
        .equals(other.getTpName())) return false;
    if (!getAssociatedDataDTOListList()
        .equals(other.getAssociatedDataDTOListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getTpName().hashCode();
    if (getAssociatedDataDTOListCount() > 0) {
      hash = (37 * hash) + ASSOCIATEDDATADTOLIST_FIELD_NUMBER;
      hash = (53 * hash) + getAssociatedDataDTOListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mps.produceData.proto.CCAssociatedDataEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mps.produceData.proto.CCAssociatedDataEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mps.produceData.proto.CCAssociatedDataEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mps.produceData.proto.CCAssociatedDataEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mps.produceData.proto.CCAssociatedDataEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mps.produceData.proto.CCAssociatedDataEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mps.produceData.proto.CCAssociatedDataEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mps.produceData.proto.CCAssociatedDataEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mps.produceData.proto.CCAssociatedDataEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mps.produceData.proto.CCAssociatedDataEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mps.produceData.proto.CCAssociatedDataEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mps.produceData.proto.CCAssociatedDataEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mps.produceData.proto.CCAssociatedDataEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CCAssociatedDataEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CCAssociatedDataEvent)
      com.mps.produceData.proto.CCAssociatedDataEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mps.produceData.proto.CCAssociatedDataEventWrapper.internal_static_CCAssociatedDataEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mps.produceData.proto.CCAssociatedDataEventWrapper.internal_static_CCAssociatedDataEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mps.produceData.proto.CCAssociatedDataEvent.class, com.mps.produceData.proto.CCAssociatedDataEvent.Builder.class);
    }

    // Construct using com.mps.produceData.proto.CCAssociatedDataEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tpName_ = "";
      if (associatedDataDTOListBuilder_ == null) {
        associatedDataDTOList_ = java.util.Collections.emptyList();
      } else {
        associatedDataDTOList_ = null;
        associatedDataDTOListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mps.produceData.proto.CCAssociatedDataEventWrapper.internal_static_CCAssociatedDataEvent_descriptor;
    }

    @java.lang.Override
    public com.mps.produceData.proto.CCAssociatedDataEvent getDefaultInstanceForType() {
      return com.mps.produceData.proto.CCAssociatedDataEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.mps.produceData.proto.CCAssociatedDataEvent build() {
      com.mps.produceData.proto.CCAssociatedDataEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mps.produceData.proto.CCAssociatedDataEvent buildPartial() {
      com.mps.produceData.proto.CCAssociatedDataEvent result = new com.mps.produceData.proto.CCAssociatedDataEvent(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.mps.produceData.proto.CCAssociatedDataEvent result) {
      if (associatedDataDTOListBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          associatedDataDTOList_ = java.util.Collections.unmodifiableList(associatedDataDTOList_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.associatedDataDTOList_ = associatedDataDTOList_;
      } else {
        result.associatedDataDTOList_ = associatedDataDTOListBuilder_.build();
      }
    }

    private void buildPartial0(com.mps.produceData.proto.CCAssociatedDataEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tpName_ = tpName_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mps.produceData.proto.CCAssociatedDataEvent) {
        return mergeFrom((com.mps.produceData.proto.CCAssociatedDataEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mps.produceData.proto.CCAssociatedDataEvent other) {
      if (other == com.mps.produceData.proto.CCAssociatedDataEvent.getDefaultInstance()) return this;
      if (!other.getTpName().isEmpty()) {
        tpName_ = other.tpName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (associatedDataDTOListBuilder_ == null) {
        if (!other.associatedDataDTOList_.isEmpty()) {
          if (associatedDataDTOList_.isEmpty()) {
            associatedDataDTOList_ = other.associatedDataDTOList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAssociatedDataDTOListIsMutable();
            associatedDataDTOList_.addAll(other.associatedDataDTOList_);
          }
          onChanged();
        }
      } else {
        if (!other.associatedDataDTOList_.isEmpty()) {
          if (associatedDataDTOListBuilder_.isEmpty()) {
            associatedDataDTOListBuilder_.dispose();
            associatedDataDTOListBuilder_ = null;
            associatedDataDTOList_ = other.associatedDataDTOList_;
            bitField0_ = (bitField0_ & ~0x00000002);
            associatedDataDTOListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAssociatedDataDTOListFieldBuilder() : null;
          } else {
            associatedDataDTOListBuilder_.addAllMessages(other.associatedDataDTOList_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tpName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList m =
                  input.readMessage(
                      com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.parser(),
                      extensionRegistry);
              if (associatedDataDTOListBuilder_ == null) {
                ensureAssociatedDataDTOListIsMutable();
                associatedDataDTOList_.add(m);
              } else {
                associatedDataDTOListBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tpName_ = "";
    /**
     * <code>string tpName = 1;</code>
     * @return The tpName.
     */
    public java.lang.String getTpName() {
      java.lang.Object ref = tpName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tpName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tpName = 1;</code>
     * @return The bytes for tpName.
     */
    public com.google.protobuf.ByteString
        getTpNameBytes() {
      java.lang.Object ref = tpName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tpName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tpName = 1;</code>
     * @param value The tpName to set.
     * @return This builder for chaining.
     */
    public Builder setTpName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tpName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string tpName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTpName() {
      tpName_ = getDefaultInstance().getTpName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string tpName = 1;</code>
     * @param value The bytes for tpName to set.
     * @return This builder for chaining.
     */
    public Builder setTpNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tpName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList> associatedDataDTOList_ =
      java.util.Collections.emptyList();
    private void ensureAssociatedDataDTOListIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        associatedDataDTOList_ = new java.util.ArrayList<com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList>(associatedDataDTOList_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOListOrBuilder> associatedDataDTOListBuilder_;

    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public java.util.List<com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList> getAssociatedDataDTOListList() {
      if (associatedDataDTOListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(associatedDataDTOList_);
      } else {
        return associatedDataDTOListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public int getAssociatedDataDTOListCount() {
      if (associatedDataDTOListBuilder_ == null) {
        return associatedDataDTOList_.size();
      } else {
        return associatedDataDTOListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList getAssociatedDataDTOList(int index) {
      if (associatedDataDTOListBuilder_ == null) {
        return associatedDataDTOList_.get(index);
      } else {
        return associatedDataDTOListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public Builder setAssociatedDataDTOList(
        int index, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList value) {
      if (associatedDataDTOListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssociatedDataDTOListIsMutable();
        associatedDataDTOList_.set(index, value);
        onChanged();
      } else {
        associatedDataDTOListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public Builder setAssociatedDataDTOList(
        int index, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder builderForValue) {
      if (associatedDataDTOListBuilder_ == null) {
        ensureAssociatedDataDTOListIsMutable();
        associatedDataDTOList_.set(index, builderForValue.build());
        onChanged();
      } else {
        associatedDataDTOListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public Builder addAssociatedDataDTOList(com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList value) {
      if (associatedDataDTOListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssociatedDataDTOListIsMutable();
        associatedDataDTOList_.add(value);
        onChanged();
      } else {
        associatedDataDTOListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public Builder addAssociatedDataDTOList(
        int index, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList value) {
      if (associatedDataDTOListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAssociatedDataDTOListIsMutable();
        associatedDataDTOList_.add(index, value);
        onChanged();
      } else {
        associatedDataDTOListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public Builder addAssociatedDataDTOList(
        com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder builderForValue) {
      if (associatedDataDTOListBuilder_ == null) {
        ensureAssociatedDataDTOListIsMutable();
        associatedDataDTOList_.add(builderForValue.build());
        onChanged();
      } else {
        associatedDataDTOListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public Builder addAssociatedDataDTOList(
        int index, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder builderForValue) {
      if (associatedDataDTOListBuilder_ == null) {
        ensureAssociatedDataDTOListIsMutable();
        associatedDataDTOList_.add(index, builderForValue.build());
        onChanged();
      } else {
        associatedDataDTOListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public Builder addAllAssociatedDataDTOList(
        java.lang.Iterable<? extends com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList> values) {
      if (associatedDataDTOListBuilder_ == null) {
        ensureAssociatedDataDTOListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, associatedDataDTOList_);
        onChanged();
      } else {
        associatedDataDTOListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public Builder clearAssociatedDataDTOList() {
      if (associatedDataDTOListBuilder_ == null) {
        associatedDataDTOList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        associatedDataDTOListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public Builder removeAssociatedDataDTOList(int index) {
      if (associatedDataDTOListBuilder_ == null) {
        ensureAssociatedDataDTOListIsMutable();
        associatedDataDTOList_.remove(index);
        onChanged();
      } else {
        associatedDataDTOListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder getAssociatedDataDTOListBuilder(
        int index) {
      return getAssociatedDataDTOListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOListOrBuilder getAssociatedDataDTOListOrBuilder(
        int index) {
      if (associatedDataDTOListBuilder_ == null) {
        return associatedDataDTOList_.get(index);  } else {
        return associatedDataDTOListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public java.util.List<? extends com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOListOrBuilder> 
         getAssociatedDataDTOListOrBuilderList() {
      if (associatedDataDTOListBuilder_ != null) {
        return associatedDataDTOListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(associatedDataDTOList_);
      }
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder addAssociatedDataDTOListBuilder() {
      return getAssociatedDataDTOListFieldBuilder().addBuilder(
          com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.getDefaultInstance());
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder addAssociatedDataDTOListBuilder(
        int index) {
      return getAssociatedDataDTOListFieldBuilder().addBuilder(
          index, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.getDefaultInstance());
    }
    /**
     * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
     */
    public java.util.List<com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder> 
         getAssociatedDataDTOListBuilderList() {
      return getAssociatedDataDTOListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOListOrBuilder> 
        getAssociatedDataDTOListFieldBuilder() {
      if (associatedDataDTOListBuilder_ == null) {
        associatedDataDTOListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList.Builder, com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOListOrBuilder>(
                associatedDataDTOList_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        associatedDataDTOList_ = null;
      }
      return associatedDataDTOListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CCAssociatedDataEvent)
  }

  // @@protoc_insertion_point(class_scope:CCAssociatedDataEvent)
  private static final com.mps.produceData.proto.CCAssociatedDataEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mps.produceData.proto.CCAssociatedDataEvent();
  }

  public static com.mps.produceData.proto.CCAssociatedDataEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CCAssociatedDataEvent>
      PARSER = new com.google.protobuf.AbstractParser<CCAssociatedDataEvent>() {
    @java.lang.Override
    public CCAssociatedDataEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CCAssociatedDataEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CCAssociatedDataEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mps.produceData.proto.CCAssociatedDataEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

