// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: first_topic.proto

package com.mps.produceData.proto;

public interface CCAssociatedDataEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CCAssociatedDataEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tpName = 1;</code>
   * @return The tpName.
   */
  java.lang.String getTpName();
  /**
   * <code>string tpName = 1;</code>
   * @return The bytes for tpName.
   */
  com.google.protobuf.ByteString
      getTpNameBytes();

  /**
   * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
   */
  java.util.List<com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList> 
      getAssociatedDataDTOListList();
  /**
   * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
   */
  com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOList getAssociatedDataDTOList(int index);
  /**
   * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
   */
  int getAssociatedDataDTOListCount();
  /**
   * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
   */
  java.util.List<? extends com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOListOrBuilder> 
      getAssociatedDataDTOListOrBuilderList();
  /**
   * <code>repeated .CCAssociatedDataEvent.AssociatedDataDTOList associatedDataDTOList = 2;</code>
   */
  com.mps.produceData.proto.CCAssociatedDataEvent.AssociatedDataDTOListOrBuilder getAssociatedDataDTOListOrBuilder(
      int index);
}
